version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"
  app:
    image: my-node-app
    ports:
      - "13000:13000"
