version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db123
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  app:
    build:
      context: .
    ports:
      - "13000:13000"
    networks:
      - mynetwork
    environment:
      DB_USER: Test
      DB_HOST: db
      DB_NAME: db123
      DB_PASSWORD: password123
      DB_PORT: 5432
      PORT: 13000
networks:
  mynetwork:
    driver: bridge
